import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { registerRoute, NavigationRoute } from 'workbox-routing'
import { NetworkFirst, StaleWhileRevalidate, NetworkOnly } from 'workbox-strategies'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { ExpirationPlugin } from 'workbox-expiration'
import { BackgroundSyncPlugin } from 'workbox-background-sync'

declare let self: ServiceWorkerGlobalScope & {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    __WB_MANIFEST: any
}

cleanupOutdatedCaches()

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST)

// Cache Google Fonts
registerRoute(
    ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
    new StaleWhileRevalidate({
        cacheName: 'google-fonts-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365 // 1 year
            })
        ]
    })
)

// ... imports

// ... imports

// Sync pending orders (Background Sync)
const bgSyncPlugin = new BackgroundSyncPlugin('dinein-offline-orders', {
    maxRetentionTime: 24 * 60 // Retry for max 24 Hours (specified in minutes)
});

// Cache Supabase API requests (Network Only + Background Sync)
registerRoute(
    ({ url }) => url.hostname.includes('supabase.co') && url.pathname.includes('/rest/v1/orders'),
    new NetworkOnly({
        plugins: [bgSyncPlugin]
    }),
    'POST'
);

// General Supabase Caching (GET)
registerRoute(
    ({ url }) => url.hostname.includes('supabase.co') && url.pathname.includes('/rest/v1/'),
    new NetworkFirst({
        cacheName: 'supabase-api-cache',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200]
            }),
            new ExpirationPlugin({
                maxEntries: 100,
                maxAgeSeconds: 60 * 60 * 24 // 24 hours
            })
        ]
    }),
    'GET'
);

// API Caching (Menu, Products) - Network First, fall back to cache
registerRoute(
    ({ url }) => url.pathname.startsWith('/api/menu') || url.pathname.startsWith('/api/products'),
    new NetworkFirst({
        cacheName: 'api-cache',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200]
            }),
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 60 * 60 * 24 // 24 hours
            })
        ]
    })
)

// Offline Fallback for Navigation
const navigationRoute = new NavigationRoute(
    async ({ event }) => {
        try {
            const response = await fetch(event.request)
            return response
        } catch {
            const cached = await caches.match('/offline.html')
            if (cached) return cached
            return new Response('Offline', { status: 503, statusText: 'Offline' })
        }
    },
    {
        denylist: [/^\/api/, /^\/assets/, /\.json$/, /\.png$/]
    }
)
registerRoute(navigationRoute)
