/**
 * Background Sync Module
 * Client-side integration for background sync with service worker
 * 
 * The actual sync event handling happens in the service worker generated by vite-plugin-pwa.
 * This module provides helpers for the main thread to register sync and listen for messages.
 */

const SYNC_TAG = 'sync-queue';

interface SyncMessage {
    type: 'SYNC_SUCCESS' | 'SYNC_FAILED' | 'PROCESS_QUEUE';
    requestId?: string;
    error?: string;
}

/**
 * Register a background sync for the order queue
 */
export async function registerBackgroundSync(): Promise<boolean> {
    if (!('serviceWorker' in navigator) || !('SyncManager' in window)) {
        console.log('[BackgroundSync] Not supported');
        return false;
    }

    try {
        const registration = await navigator.serviceWorker.ready;
        // @ts-expect-error - background sync API not in standard TS types
        await registration.sync.register(SYNC_TAG);
        console.log('[BackgroundSync] Registered sync:', SYNC_TAG);
        return true;
    } catch (error) {
        console.error('[BackgroundSync] Registration failed:', error);
        return false;
    }
}

/**
 * Listen for sync messages from the service worker
 */
export function onSyncMessage(callback: (message: SyncMessage) => void): () => void {
    const handler = (event: MessageEvent) => {
        if (event.data?.type === 'SYNC_SUCCESS' ||
            event.data?.type === 'SYNC_FAILED' ||
            event.data?.type === 'PROCESS_QUEUE') {
            callback(event.data as SyncMessage);
        }
    };

    navigator.serviceWorker?.addEventListener('message', handler);

    return () => {
        navigator.serviceWorker?.removeEventListener('message', handler);
    };
}

/**
 * Check if background sync is supported
 */
export function isBackgroundSyncSupported(): boolean {
    return 'serviceWorker' in navigator && 'SyncManager' in window;
}

export { SYNC_TAG };
export type { SyncMessage };
