/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
        "./pages/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
        "./context/**/*.{js,ts,jsx,tsx}",
        "./services/**/*.{js,ts,jsx,tsx}",
        "./utils/**/*.{js,ts,jsx,tsx}"
    ],
    darkMode: ['class', '[data-theme="dark"]'],
    theme: {
        extend: {
            colors: {
                background: 'var(--bg-main)',
                surface: 'var(--bg-surface)',
                'surface-highlight': 'var(--bg-surface-highlight)',
                elevated: 'var(--bg-elevated)',
                foreground: 'var(--text-main)',
                muted: 'var(--text-muted)',
                subtle: 'var(--text-subtle)',
                border: 'var(--border-color)',
                'border-strong': 'var(--border-strong)',
                glass: "var(--glass-bg)",
                'glass-strong': "var(--glass-bg-strong)",
                glassBorder: "var(--glass-border)",
                primary: {
                    50: 'var(--color-primary-50)',
                    100: 'var(--color-primary-100)',
                    200: 'var(--color-primary-200)',
                    300: 'var(--color-primary-300)',
                    400: 'var(--color-primary-400)',
                    DEFAULT: 'var(--color-primary-500)',
                    500: 'var(--color-primary-500)',
                    600: 'var(--color-primary-600)',
                    700: 'var(--color-primary-700)',
                    800: 'var(--color-primary-800)',
                    900: 'var(--color-primary-900)',
                },
                secondary: {
                    50: 'var(--color-secondary-50)',
                    100: 'var(--color-secondary-100)',
                    200: 'var(--color-secondary-200)',
                    300: 'var(--color-secondary-300)',
                    400: 'var(--color-secondary-400)',
                    DEFAULT: 'var(--color-secondary-500)',
                    500: 'var(--color-secondary-500)',
                    600: 'var(--color-secondary-600)',
                    700: 'var(--color-secondary-700)',
                    800: 'var(--color-secondary-800)',
                    900: 'var(--color-secondary-900)',
                },
                accent: {
                    DEFAULT: 'var(--color-accent-500)',
                    500: 'var(--color-accent-500)'
                },
                ink: 'var(--color-ink)',
                success: 'var(--color-success)',
                'success-bg': 'var(--color-success-bg)',
                warning: 'var(--color-warning)',
                'warning-bg': 'var(--color-warning-bg)',
                error: 'var(--color-error)',
                'error-bg': 'var(--color-error-bg)',
                info: 'var(--color-info)',
                'info-bg': 'var(--color-info-bg)',
            },
            spacing: {
                'safe-top': 'var(--safe-top)',
                'safe-bottom': 'var(--safe-bottom)',
                'safe-left': 'var(--safe-left)',
                'safe-right': 'var(--safe-right)',
            },
            borderRadius: {
                'glass': 'var(--radius-2xl)',
                '3xl': 'var(--radius-3xl)',
            },
            backdropBlur: {
                xs: 'var(--blur-sm)',
                sm: 'var(--blur-md)',
                DEFAULT: 'var(--blur-lg)',
                lg: 'var(--blur-xl)',
                xl: 'var(--blur-2xl)',
                '2xl': 'var(--blur-3xl)',
            },
            boxShadow: {
                'glass': 'var(--shadow-glass)',
                'glass-lg': 'var(--shadow-glass-lg)',
                'glass-inset': 'var(--shadow-glass-inset)',
                'glow': 'var(--shadow-glow-primary)',
                'glow-secondary': 'var(--shadow-glow-secondary)',
                'glow-accent': 'var(--shadow-glow-accent)',
                'elev-1': 'var(--shadow-elev-1)',
                'elev-2': 'var(--shadow-elev-2)',
            },
            fontFamily: {
                display: ['var(--font-display)', 'serif'],
                body: ['var(--font-body)', 'system-ui', 'sans-serif'],
                accent: ['var(--font-accent)', 'serif'],
                mono: ['var(--font-mono)', 'monospace'],
            },
            fontSize: {
                '2xs': ['var(--text-xs)', { lineHeight: 'var(--leading-normal)' }],
            },
            minHeight: {
                'touch': 'var(--min-touch-target)',
            },
            minWidth: {
                'touch': 'var(--min-touch-target)',
            },
            zIndex: {
                'below': 'var(--z-below)',
                'elevated': 'var(--z-elevated)',
                'dropdown': 'var(--z-dropdown)',
                'sticky': 'var(--z-sticky)',
                'overlay': 'var(--z-overlay)',
                'modal': 'var(--z-modal)',
                'popover': 'var(--z-popover)',
                'toast': 'var(--z-toast)',
                'tooltip': 'var(--z-tooltip)',
                'max': 'var(--z-max)',
            },
            transitionDuration: {
                'fast': 'var(--duration-fast)',
                'normal': 'var(--duration-normal)',
                'slow': 'var(--duration-slow)',
            },
            transitionTimingFunction: {
                'ios': 'var(--ease-ios)',
                'bounce': 'var(--ease-bounce)',
                'spring': 'var(--ease-spring)',
            },
            animation: {
                'fade-in': 'fadeIn var(--duration-slow) var(--ease-out)',
                'fade-out': 'fadeOut var(--duration-slow) var(--ease-out)',
                'slide-up': 'slideUp var(--duration-slow) var(--ease-ios)',
                'slide-down': 'slideDown var(--duration-slow) var(--ease-ios)',
                'slide-up-fade': 'slideUpFade var(--duration-slow) var(--ease-ios)',
                'bounce-gentle': 'bounceGentle var(--duration-slower) var(--ease-in-out)',
                'scale-in': 'scaleIn var(--duration-normal) var(--ease-spring)',
                'scale-out': 'scaleOut var(--duration-fast) var(--ease-in)',
                'glass-in': 'glassIn var(--duration-slow) var(--ease-spring)',
                'shimmer': 'shimmer 2s infinite linear',
                'pulse-slow': 'pulse 3s infinite',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                fadeOut: {
                    '0%': { opacity: '1' },
                    '100%': { opacity: '0' },
                },
                slideUp: {
                    '0%': { transform: 'translateY(100%)' },
                    '100%': { transform: 'translateY(0)' },
                },
                slideDown: {
                    '0%': { transform: 'translateY(-100%)' },
                    '100%': { transform: 'translateY(0)' },
                },
                slideUpFade: {
                    '0%': { transform: 'translateY(16px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                bounceGentle: {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-10px)' },
                },
                scaleIn: {
                    '0%': { transform: 'scale(0.95)', opacity: '0' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                scaleOut: {
                    '0%': { transform: 'scale(1)', opacity: '1' },
                    '100%': { transform: 'scale(0.95)', opacity: '0' },
                },
                glassIn: {
                    '0%': {
                        transform: 'scale(0.95) translateY(8px)',
                        opacity: '0',
                        backdropFilter: 'blur(0)',
                    },
                    '100%': {
                        transform: 'scale(1) translateY(0)',
                        opacity: '1',
                        backdropFilter: 'blur(var(--blur-xl))',
                    },
                },
                shimmer: {
                    '0%': { backgroundPosition: '-1000px 0' },
                    '100%': { backgroundPosition: '1000px 0' },
                },
            },
        }
    },
    plugins: [],
}
